name: cd
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - main  # Wird nur getriggered, wenn Code in "master" gepusht wird (z.B. nach einem Merge)

jobs:
  Kubernetes:
    runs-on: [self-hosted, linux, x64, multipass]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4      
      - name: Check and Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
        id: install

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Replace and Apply Kubernetes Manifests
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: |
            .k8s/namespace.yml
            .k8s/deployment.yml
            .k8s/service.yml
            .k8s/ingress.yml
          replacement-method: defined